name: learn_machine_learning_env
channels:
  - defaults
dependencies:
  - python=3.9
  - tensorflow-gpu
  - keras-tuner
  - pip
  - pip:
    - autogluon==1.3.1
    - scikit-learn==1.6.1
    - numpy
    - seaborn
    - pandas
    - nbformat>=4.2.0
    - Pygments==2.19.1
    - plotly