name: learn_machine_learning_env
channels:
  - defaults
dependencies:
  - python=3.12.9
  - pandas=2.2.3
  - numpy=2.2.4
  - plotly=6.0.1
  - Pygments=2.19.1
  - nbformat>=4.2.0
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - autogluon=1.3.1
  - pip:
    - tensorflow[and-cuda]